language: ruby
branches:
  only: [master]
services:
  - mysql
rvm:
  - 2.5
  - 2.6
  - 2.7
matrix:
  include:
    - rvm: 2.7
      env: RUBYOPT="--jit"
  allow_failures:
    - env: RUBYOPT="--jit"

before_install: ruby -e "File.write('Gemfile.lock', File.read('Gemfile.lock').split('BUNDLED WITH').first)"
