language: ruby
cache: bundler
sudo: false
dist: precise
branches:
  only: master
before_install: gem update --system # needed for 2.5.0
rvm:
  - 1.9
  - 2.0
  - 2.1
  - 2.2
  - 2.3
  - 2.4
  - 2.5.0 # TODO: use 2.5

